version: "3.8"  # Use the latest version compatible with your Docker setup
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "4000:4000"
    restart: always  # Restart policy for the backend service
    volumes:
      - ./backend:/usr/src/workspace  # Mount the backend directory

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always  # Restart policy for the frontend service
    depends_on:
      - backend  # Ensure frontend starts after backend
    volumes:
      - ./frontend:/usr/src/workspace  # Mount the frontend directory

networks:
  app-network:
    driver: bridge