# site name
site_name: Template

# site url
site_url: https://TEMPLATE.com/

# pages
nav:
  - Home: index.md

# theme
theme:
  name: "material"

# plugin
plugins:
  - mkdocstrings
  - search

# for mathjax
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# for mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
