repos:
  # General Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: forbid-new-submodules
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
        types_or: [python]
      - id: trailing-whitespace
        types_or: [python]
      - id: debug-statements
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  # Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types_or: [python, pyi]
        entry: "black"
        args: ["--config", "pyproject.toml"]
        exclude: "docs/_pygments/monokai.py"

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix"]

  # Format Docstring Quotes
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args:
          [
            "--black",
            "--make-summary-multi-line",
            "--pre-summary-newline",
            "--blank",
            "--recursive",
            "--in-place",
          ]

  # Check for trailing commas
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
        types: [python]

  # Check Commit Message for Style
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      # - id: gitlint-ci

  # Check for common misspellings
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        description: Checks for common misspellings.
        types_or: [python, cython, rst, markdown]
        args: ["-L", "crate,ot,socio-economic,zar"]

  # Static Type Checking for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args: ["--config", "pyproject.toml", "--allow-incomplete-defs"]
        additional_dependencies:
          [
            msgspec,
            types-frozendict,
            types-pytz,
            types-redis,
            types-requests,
            types-toml,
          ]

  # Strip out output from Jupyter Notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
